### ISSUE TITLE
Add Turn Penalty

### ISSUE THREAD

**Issue by ray-ngo** [ray-ngo/V2.3#6]
Add Turn Penalty Option

**Comment by cogtesting2** [comment]
I am working on this

**Comment by cogtesting2** [comment]
@cogtesting1 : Any idea to make ec22fbe better?

**Comment by cogtesting1** [comment]
@cogtesting Revised the script. Thought on e891a643a26fb68a41648979015ff3c462da407e?

**Comment by cogtesting2** [comment]
@cogtesting1 👍 
@ray-ngo : Approve?

**Comment by ray-ngo** [comment]
👍
